name: dritte_chance_monitor_app
description: "A lyrics monitor application for DritteChance."
publish_to: 'none'
version: 1.4.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Fonts
  google_fonts: ^6.2.1

  # Others
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^4.0.0

  # Release stuff
  msix: ^3.16.8

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg

msix_config:
  display_name: DritteChance Monitor
  publisher_display_name: coderave
  identity_name: dev.coderave.dritte-chance-monitor-app
  msix_version: 1.4.0.0
  signtool_options: /td sha256